# Generated by Django 3.2 on 2024-06-14 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_review_id_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10, message='Введите цифру от 1 до 10.'), django.core.validators.MinValueValidator(1, message='Введите цифру от 1 до 10')], verbose_name='Оценка произведения'),
        ),
    ]
