# Generated by Django 3.2 on 2024-06-14 08:54

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_review_id_comment_review'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(check=models.Q(year__lte=django.db.models.functions.datetime.ExtractYear(django.db.models.functions.datetime.Now())), name='year must be less than or equal today'),
        ),
    ]
