# Generated by Django 3.2 on 2024-06-14 09:07

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_title_year must be less than or equal today'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='year must be less than or equal today',
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[reviews.models.lte_current_year_validator], verbose_name='Год создания произведения'),
        ),
    ]
