# Generated by Django 3.2 on 2024-06-14 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Оценка должна быть не более 10'), django.core.validators.MinValueValidator(1, message='Оценка должна быть не менее 1')], verbose_name='Оценка произведения'),
        ),
    ]
